on:
  push:
    branches:
    - master
    - release/*
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.yeresearch.ru
        username: a0500681
        password: ${{ secrets.ftp_password }}
        server-dir: domains/yeresearch.ru/public_html/boyz/
        protocol: ftp
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/boyz/**